# Generated by Django 4.2.3 on 2023-12-14 12:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="session_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Stripe Session ID"
            ),
        ),
    ]
