# Generated by Django 4.2.3 on 2023-12-14 13:48

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0002_property_session_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="PropertyCategories",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category_name",
                    models.CharField(
                        max_length=250, unique=True, verbose_name="Category Name"
                    ),
                ),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        always_update=True,
                        editable=False,
                        populate_from="category_name",
                        unique=True,
                    ),
                ),
                (
                    "category_description",
                    models.TextField(
                        default="Default description",
                        verbose_name="Category Description",
                    ),
                ),
                (
                    "category_image",
                    models.ImageField(
                        default="/house_sample.jpg",
                        upload_to="",
                        verbose_name="Category Image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Property Category",
                "verbose_name_plural": "Property Categories",
            },
        ),
        migrations.AddField(
            model_name="property",
            name="categoty",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="property_category",
                to="properties.propertycategories",
                verbose_name="Property Category",
            ),
        ),
    ]
