# Generated by Django 4.2.3 on 2023-12-14 13:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0003_propertycategories_property_categoty"),
    ]

    operations = [
        migrations.RenameField(
            model_name="property",
            old_name="categoty",
            new_name="category",
        ),
    ]
