# Generated by Django 4.2.3 on 2023-12-14 13:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0004_rename_categoty_property_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="is_approved",
            field=models.BooleanField(default=False, verbose_name="Is Approved"),
        ),
        migrations.AddField(
            model_name="property",
            name="is_archived",
            field=models.BooleanField(default=False, verbose_name="Is Archived"),
        ),
        migrations.AddField(
            model_name="property",
            name="is_available",
            field=models.BooleanField(default=True, verbose_name="Is Available"),
        ),
        migrations.AddField(
            model_name="property",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="Is Deleted"),
        ),
        migrations.AddField(
            model_name="property",
            name="is_featured",
            field=models.BooleanField(default=False, verbose_name="Is Featured"),
        ),
        migrations.AddField(
            model_name="property",
            name="is_hot_deal",
            field=models.BooleanField(default=False, verbose_name="Is Hot Deal"),
        ),
        migrations.AddField(
            model_name="property",
            name="is_new",
            field=models.BooleanField(default=False, verbose_name="Is New"),
        ),
        migrations.AddField(
            model_name="property",
            name="is_occupied",
            field=models.BooleanField(default=False, verbose_name="Is Occupied"),
        ),
        migrations.AddField(
            model_name="property",
            name="is_published",
            field=models.BooleanField(default=False, verbose_name="Is Published"),
        ),
        migrations.AddField(
            model_name="property",
            name="is_rented",
            field=models.BooleanField(default=False, verbose_name="Is Rented"),
        ),
        migrations.AddField(
            model_name="property",
            name="is_sold",
            field=models.BooleanField(default=False, verbose_name="Is Sold"),
        ),
        migrations.AddField(
            model_name="property",
            name="is_top_rated",
            field=models.BooleanField(default=False, verbose_name="Is Top Rated"),
        ),
        migrations.AddField(
            model_name="property",
            name="is_verified",
            field=models.BooleanField(default=False, verbose_name="Is Verified"),
        ),
    ]
