# Generated by Django 4.2.3 on 2023-12-14 14:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0005_property_is_approved_property_is_archived_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="propertycategories",
            old_name="category_description",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="propertycategories",
            old_name="category_image",
            new_name="image",
        ),
        migrations.RenameField(
            model_name="propertycategories",
            old_name="category_name",
            new_name="name",
        ),
    ]
