# Generated by Django 4.2.3 on 2023-12-17 22:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "properties",
            "0006_rename_category_description_propertycategories_description_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="propertyviews",
            options={
                "verbose_name": "Total Property View",
                "verbose_name_plural": "Total Property Views",
            },
        ),
        migrations.AlterField(
            model_name="property",
            name="description",
            field=models.TextField(
                default="Default description", unique=True, verbose_name="Description"
            ),
        ),
    ]
