# Generated by Django 4.2.3 on 2023-12-19 14:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0007_alter_propertyviews_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="property_valuation_report",
            field=models.TextField(
                blank=True,
                help_text="Property valuation report",
                null=True,
                verbose_name="Property Valuation Report",
            ),
        ),
    ]
