# Generated by Django 4.2.3 on 2023-12-19 15:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0009_property_zip_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="furnished",
            field=models.BooleanField(default=False, verbose_name="Furnished"),
        ),
        migrations.AddField(
            model_name="property",
            name="parking",
            field=models.BooleanField(default=False, verbose_name="Parking"),
        ),
    ]
