# Generated by Django 4.2.3 on 2023-12-23 23:23

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0010_property_furnished_property_parking"),
    ]

    operations = [
        migrations.AlterField(
            model_name="propertycategories",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                always_update=True, editable=False, populate_from="name", unique=True
            ),
        ),
    ]
