# Generated by Django 4.2.3 on 2023-12-28 00:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0011_alter_propertycategories_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="is_favorite",
            field=models.BooleanField(default=False, verbose_name="Is Favorite"),
        ),
    ]
