# Generated by Django 4.2.3 on 2023-12-28 00:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ratings", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rating",
            options={"verbose_name": "Rating", "verbose_name_plural": "Ratings"},
        ),
        migrations.RemoveField(
            model_name="rating",
            name="property",
        ),
    ]
